### ISSUE TITLE
bins.py not working

### ISSUE THREAD

**Issue by dummys** [mak/libzpy#1]
Hello,

I'm trying to use your bins.py but nothing works.

-> $ python2 bins.py --list --verbose --fin config.bin --do extract
ERROR:**main**:Fail to process element [extract], reason : Exception('Fail to parse line !',) 
Traceback (most recent call last):
  File "bins.py", line 125, in <module>
    x = processElement(elem)
  File "bins.py", line 61, in processElement
    raise Exception("Fail to parse line !")
Exception: Fail to parse line !
foo

-> $ python2 bins.py --list --verbose --fin config.bin --do extract
ERROR:**main**:Fail to process element [extract], reason : Exception('Fail to parse line !',) 
Traceback (most recent call last):
  File "bins.py", line 125, in <module>
    x = processElement(elem)
  File "bins.py", line 61, in processElement
    raise Exception("Fail to parse line !")
Exception: Fail to parse line !
foo

-> $ python2 bins.py --list --verbose --fin config.bin --do zeus  
ERROR:**main**:Fail to process element [zeus], reason : Exception('Fail to parse line !',) 
Traceback (most recent call last):
  File "bins.py", line 125, in <module>
    x = processElement(elem)
  File "bins.py", line 61, in processElement
    raise Exception("Fail to parse line !")
Exception: Fail to parse line !
foo

-> $ python2 bins.py --list --verbose --fin config.bin --do unpack
ERROR:**main**:Fail to process element [unpack], reason : Exception('Fail to parse line !',) 
Traceback (most recent call last):
  File "bins.py", line 125, in <module>
    x = processElement(elem)
  File "bins.py", line 61, in processElement
    raise Exception("Fail to parse line !")
Exception: Fail to parse line !
foo

Can you explain how the tools works ?
I tried to add as "do" every file I found in the modules folder, but not working.

**Comment by mak** [comment]
format for bins.py is quite odd, (blame @k3idii for it ;)
module/action
so in your case

 python2 bins.py --list --verbose --fin config.bin --do zeus/unpack

**Comment by dummys** [comment]
Oh sweet.

Question, is the bins used to extract the config.bin downloaded by the malware from the url contains in the first config file ?

**Comment by dummys** [comment]
Seems to still have a bug:

-> $ python2 bins.py --list --verbose --fin config.bin --do zeus/unpack                             1 ↵
[v] Work work ... 
[v] Got [351] bytes from file
[v] {'par': <module 'modules.zeus' from '/libzpy/modules/zeus.pyc'>, 'args': {}, 'func': <function unpack at 0x7fe1b7c1b9b0>}

Doing a ctrl+c:

^CTraceback (most recent call last):
  File "bins.py", line 145, in <module>
    data = elem['func'](data,verb,**elem['args']) 
  File "libzpy/modules/zeus.py", line 11, in unpack
    return t.unpack(data,verb,zeus,verify)
  File "libzpy/modules/template.py", line 22, in unpack
    itm = mod.Item(data)
  File "libzpy/structs/zeus.py", line 76, in **init**
    self._cfgids_n = self._cfgids.__class__(map(reversed, self._cfgids.items()))
KeyboardInterrupt

**Comment by k3idii** [comment]
Share config.bin , will debug

**Comment by dummys** [comment]
http://s000.tinyupload.com/index.php?file_id=09890559596742616167

thx taking time :dancer:

**Comment by mak** [comment]
this is not zeus config

**Comment by dummys** [comment]
Yes it's the config.bin crypted. Do I need to first decrypt it with the key RC4 Config Key I found with zeusscan in volatility ?

**Comment by mak** [comment]
yep, this is just a parser

**Comment by dummys** [comment]
Ok but the cr_tools.py can be used for that right ? How can I be sure that the config file is not xored before ?

In vol.py, zeusscan told me that it's a 1.x zeus version and I get a xor key, a RC4 Config Key and a RC4 Credential key.

**Comment by mak** [comment]
yeah you can use it, there should be rc4 code to do it 
but tbh im not sure this tool will help you with zeus 1.x - i never tested it on such old malware

do you mind sharing a sample?

**Comment by dummys** [comment]
ok it's ok.

python2 cr_tools.py -f ../config.bin -k ../../key_good -v -t bin > config_uncrypted

Thanks a lot for your tools.

**Comment by dummys** [comment]
Yes If you want the sample I can share, no problem

**Comment by mak** [comment]
nah if it works for you i'ts ok ;]
still have plenty of others to sink my teeth in ;]

**Comment by dummys** [comment]
:) have fun and thx
